import Head from 'next/head'
import { GetStaticProps } from 'next'
import { StrapiApiResponse, StrapiPage } from '@/common/types/strapi'
import { getResource } from '@/lib/strapi'
import { RequestError } from '@/common/types/resources'
import { GeneralServerConfig } from '@/common/constants/server'

interface Props {
  pages: StrapiPage[]
}

export const getStaticProps: GetStaticProps<Props> = async (ctx) => {
  const defaultPageConfig = {
    revalidate: GeneralServerConfig.revalidationTime
  }
  
  const response: StrapiApiResponse<StrapiPage[]> | RequestError = await getResource<StrapiPage[]>('/pages')
  
  if ("data" in response) {
    return {
      ...defaultPageConfig,
      props: {
        pages: response.data
      }
    }
  }
  
  return {
    ...defaultPageConfig,
    redirect: {
      destination: '/500',
      permanent: false
    }
  }


}

export default function Home({ pages }: Props) {
  return (
    <>
      <Head>
        <title>Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
        Available Pages
      </h1>
      { pages.map((page: StrapiPage) => 
        <span key={page.attributes.slug}>{page.attributes.title}</span>
      )}
      </main>
    </>
  )
}
