import Head from 'next/head'
import { GetStaticProps } from 'next'
import { StrapiApiResponse, StrapiPage } from '@/common/types/strapi'
import { getResource } from '@/server/strapi'
import { RequestError, ServerProps } from '@/common/types/server'

interface Props extends ServerProps {
  pages: StrapiPage[]
}

export const getStaticProps: GetStaticProps<Props> = async (ctx) => {
  try {
    const response: StrapiApiResponse<StrapiPage[]> | RequestError = await getResource<StrapiPage[]>('/pages')
    
    if ("data" in response) {
      return {
        props: {
          pages: response.data
        }
      }
    }
    
    return {
      props: {
        error: response,
        pages: []
      }
    }
  } catch(e) {
    return {
      props: {
        pages: [],
        error: { status: 500, message: 'Could not fetch the pages...' }
      }
    }
  }

}

export default function Home({ pages }: Props) {
  return (
    <>
      <Head>
        <title>Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
        Available Pages
      </h1>
      { pages.map((page: StrapiPage) => 
        <span key={page.attributes.slug}>{page.attributes.title}</span>
      )}
      </main>
    </>
  )
}
